/* SPDX-License-Identifier: Apache-2.0 */
#pragma once

typedef enum {
  INVALID_RESOURCE = 0,
  RESOURCE_ID_INVALID = 0,
  RESOURCE_ID_FONT_FALLBACK_INTERNAL = 1,
  RESOURCE_ID_NOTIFICATION_GENERIC_TINY = 110,
  RESOURCE_ID_EMOJI_HEART_LARGE = 1000,
  RESOURCE_ID_EMOJI_THUMBS_UP_LARGE,
  RESOURCE_ID_EMOJI_BIG_OPEN_SMILE_LARGE,
  RESOURCE_ID_EMOJI_SMILING_WITH_TEETH_LARGE,
  RESOURCE_ID_EMOJI_LAUGHING_WITH_TEARS_LARGE,
  RESOURCE_ID_EMOJI_BIG_SMILE_LARGE,
  RESOURCE_ID_EMOJI_WINK_LARGE,
  RESOURCE_ID_EMOJI_SMILING_BLUSH_LARGE,
  RESOURCE_ID_EMOJI_SMILING_HEARTS_LARGE,
  RESOURCE_ID_EMOJI_KISSING_WITH_HEART_LARGE,
  RESOURCE_ID_EMOJI_WINK_TONGUE_LARGE,
  RESOURCE_ID_EMOJI_SAD_LARGE,
} ResourceId;
