/* SPDX-License-Identifier: Apache-2.0 */
// Generated by zephyr-port-notes/tools/gen_pbl_table_stubs.py: weak stubs for
// exported-symbol-table entries the port does not link yet. A real
// definition anywhere in the build overrides the stub.
#include <stdint.h>
#include <zephyr/sys/printk.h>

static void prv_missing(const char *name) { printk("APPLIB_MISSING %s\n", name); }

__attribute__((weak)) intptr_t accel_data_service_subscribe(void) { prv_missing("accel_data_service_subscribe"); return 0; }
__attribute__((weak)) intptr_t accel_data_service_subscribe__deprecated(void) { prv_missing("accel_data_service_subscribe__deprecated"); return 0; }
__attribute__((weak)) intptr_t accel_data_service_unsubscribe(void) { prv_missing("accel_data_service_unsubscribe"); return 0; }
__attribute__((weak)) intptr_t accel_raw_data_service_subscribe(void) { prv_missing("accel_raw_data_service_subscribe"); return 0; }
__attribute__((weak)) intptr_t accel_service_peek(void) { prv_missing("accel_service_peek"); return 0; }
__attribute__((weak)) intptr_t accel_service_set_samples_per_update(void) { prv_missing("accel_service_set_samples_per_update"); return 0; }
__attribute__((weak)) intptr_t accel_service_set_sampling_rate(void) { prv_missing("accel_service_set_sampling_rate"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_add_to_window(void) { prv_missing("action_bar_layer_legacy2_add_to_window"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_clear_icon(void) { prv_missing("action_bar_layer_legacy2_clear_icon"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_create(void) { prv_missing("action_bar_layer_legacy2_create"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_destroy(void) { prv_missing("action_bar_layer_legacy2_destroy"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_get_layer(void) { prv_missing("action_bar_layer_legacy2_get_layer"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_remove_from_window(void) { prv_missing("action_bar_layer_legacy2_remove_from_window"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_set_background_color_2bit(void) { prv_missing("action_bar_layer_legacy2_set_background_color_2bit"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_set_click_config_provider(void) { prv_missing("action_bar_layer_legacy2_set_click_config_provider"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_set_context(void) { prv_missing("action_bar_layer_legacy2_set_context"); return 0; }
__attribute__((weak)) intptr_t action_bar_layer_legacy2_set_icon(void) { prv_missing("action_bar_layer_legacy2_set_icon"); return 0; }
__attribute__((weak)) intptr_t alarm_service_peek_next(void) { prv_missing("alarm_service_peek_next"); return 0; }
__attribute__((weak)) intptr_t animation_legacy2_get_context(void) { prv_missing("animation_legacy2_get_context"); return 0; }
__attribute__((weak)) intptr_t animation_legacy2_unschedule_all(void) { prv_missing("animation_legacy2_unschedule_all"); return 0; }
__attribute__((weak)) intptr_t app_comm_get_sniff_interval(void) { prv_missing("app_comm_get_sniff_interval"); return 0; }
__attribute__((weak)) intptr_t app_comm_set_sniff_interval(void) { prv_missing("app_comm_set_sniff_interval"); return 0; }
__attribute__((weak)) intptr_t app_focus_service_subscribe(void) { prv_missing("app_focus_service_subscribe"); return 0; }
__attribute__((weak)) intptr_t app_get_system_locale(void) { prv_missing("app_get_system_locale"); return 0; }
__attribute__((weak)) intptr_t app_glance_add_slice(void) { prv_missing("app_glance_add_slice"); return 0; }
__attribute__((weak)) intptr_t app_glance_reload(void) { prv_missing("app_glance_reload"); return 0; }
__attribute__((weak)) intptr_t app_launch_get_quick_launch_action(void) { prv_missing("app_launch_get_quick_launch_action"); return 0; }
__attribute__((weak)) intptr_t app_light_enable(void) { prv_missing("app_light_enable"); return 0; }
__attribute__((weak)) intptr_t app_light_enable_interaction(void) { prv_missing("app_light_enable_interaction"); return 0; }
__attribute__((weak)) intptr_t app_light_is_on(void) { prv_missing("app_light_is_on"); return 0; }
__attribute__((weak)) intptr_t app_light_set_color(void) { prv_missing("app_light_set_color"); return 0; }
__attribute__((weak)) intptr_t app_light_set_color_rgb888(void) { prv_missing("app_light_set_color_rgb888"); return 0; }
__attribute__((weak)) intptr_t app_light_set_system_color(void) { prv_missing("app_light_set_system_color"); return 0; }
__attribute__((weak)) intptr_t app_log(void) { prv_missing("app_log"); return 0; }
__attribute__((weak)) intptr_t app_message_deregister_callbacks(void) { prv_missing("app_message_deregister_callbacks"); return 0; }
__attribute__((weak)) intptr_t app_message_get_context(void) { prv_missing("app_message_get_context"); return 0; }
__attribute__((weak)) intptr_t app_message_inbox_size_maximum(void) { prv_missing("app_message_inbox_size_maximum"); return 0; }
__attribute__((weak)) intptr_t app_message_open(void) { prv_missing("app_message_open"); return 0; }
__attribute__((weak)) intptr_t app_message_outbox_begin(void) { prv_missing("app_message_outbox_begin"); return 0; }
__attribute__((weak)) intptr_t app_message_outbox_send(void) { prv_missing("app_message_outbox_send"); return 0; }
__attribute__((weak)) intptr_t app_message_outbox_size_maximum(void) { prv_missing("app_message_outbox_size_maximum"); return 0; }
__attribute__((weak)) intptr_t app_message_register_inbox_dropped(void) { prv_missing("app_message_register_inbox_dropped"); return 0; }
__attribute__((weak)) intptr_t app_message_register_inbox_received(void) { prv_missing("app_message_register_inbox_received"); return 0; }
__attribute__((weak)) intptr_t app_message_register_outbox_failed(void) { prv_missing("app_message_register_outbox_failed"); return 0; }
__attribute__((weak)) intptr_t app_message_register_outbox_sent(void) { prv_missing("app_message_register_outbox_sent"); return 0; }
__attribute__((weak)) intptr_t app_message_set_context(void) { prv_missing("app_message_set_context"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_attribute_begin_write(void) { prv_missing("app_smartstrap_attribute_begin_write"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_attribute_create(void) { prv_missing("app_smartstrap_attribute_create"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_attribute_destroy(void) { prv_missing("app_smartstrap_attribute_destroy"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_attribute_end_write(void) { prv_missing("app_smartstrap_attribute_end_write"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_attribute_get_attribute_id(void) { prv_missing("app_smartstrap_attribute_get_attribute_id"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_attribute_get_service_id(void) { prv_missing("app_smartstrap_attribute_get_service_id"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_attribute_read(void) { prv_missing("app_smartstrap_attribute_read"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_service_is_available(void) { prv_missing("app_smartstrap_service_is_available"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_set_timeout(void) { prv_missing("app_smartstrap_set_timeout"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_subscribe(void) { prv_missing("app_smartstrap_subscribe"); return 0; }
__attribute__((weak)) intptr_t app_smartstrap_unsubscribe(void) { prv_missing("app_smartstrap_unsubscribe"); return 0; }
__attribute__((weak)) intptr_t app_sync_deinit(void) { prv_missing("app_sync_deinit"); return 0; }
__attribute__((weak)) intptr_t app_sync_get(void) { prv_missing("app_sync_get"); return 0; }
__attribute__((weak)) intptr_t app_sync_init(void) { prv_missing("app_sync_init"); return 0; }
__attribute__((weak)) intptr_t app_sync_set(void) { prv_missing("app_sync_set"); return 0; }
__attribute__((weak)) intptr_t app_text_layer_legacy2_get_content_size(void) { prv_missing("app_text_layer_legacy2_get_content_size"); return 0; }
__attribute__((weak)) intptr_t app_touch_navigation_enable(void) { prv_missing("app_touch_navigation_enable"); return 0; }
__attribute__((weak)) intptr_t app_wakeup_cancel(void) { prv_missing("app_wakeup_cancel"); return 0; }
__attribute__((weak)) intptr_t app_wakeup_cancel_all(void) { prv_missing("app_wakeup_cancel_all"); return 0; }
__attribute__((weak)) intptr_t app_wakeup_get_launch_event(void) { prv_missing("app_wakeup_get_launch_event"); return 0; }
__attribute__((weak)) intptr_t app_wakeup_query(void) { prv_missing("app_wakeup_query"); return 0; }
__attribute__((weak)) intptr_t app_wakeup_schedule(void) { prv_missing("app_wakeup_schedule"); return 0; }
__attribute__((weak)) intptr_t app_wakeup_service_subscribe(void) { prv_missing("app_wakeup_service_subscribe"); return 0; }
__attribute__((weak)) intptr_t app_worker_is_running(void) { prv_missing("app_worker_is_running"); return 0; }
__attribute__((weak)) intptr_t app_worker_kill(void) { prv_missing("app_worker_kill"); return 0; }
__attribute__((weak)) intptr_t app_worker_launch(void) { prv_missing("app_worker_launch"); return 0; }
__attribute__((weak)) intptr_t app_worker_message_subscribe(void) { prv_missing("app_worker_message_subscribe"); return 0; }
__attribute__((weak)) intptr_t app_worker_message_unsubscribe(void) { prv_missing("app_worker_message_unsubscribe"); return 0; }
__attribute__((weak)) intptr_t app_worker_send_message(void) { prv_missing("app_worker_send_message"); return 0; }
__attribute__((weak)) intptr_t applib_resource_load(void) { prv_missing("applib_resource_load"); return 0; }
__attribute__((weak)) intptr_t applib_resource_load_byte_range(void) { prv_missing("applib_resource_load_byte_range"); return 0; }
__attribute__((weak)) intptr_t applib_resource_size(void) { prv_missing("applib_resource_size"); return 0; }
__attribute__((weak)) intptr_t backlight_service_subscribe(void) { prv_missing("backlight_service_subscribe"); return 0; }
__attribute__((weak)) intptr_t backlight_service_unsubscribe(void) { prv_missing("backlight_service_unsubscribe"); return 0; }
__attribute__((weak)) intptr_t clock_to_timestamp(void) { prv_missing("clock_to_timestamp"); return 0; }
__attribute__((weak)) intptr_t compass_service_peek(void) { prv_missing("compass_service_peek"); return 0; }
__attribute__((weak)) intptr_t compass_service_set_heading_filter(void) { prv_missing("compass_service_set_heading_filter"); return 0; }
__attribute__((weak)) intptr_t compass_service_subscribe(void) { prv_missing("compass_service_subscribe"); return 0; }
__attribute__((weak)) intptr_t compass_service_unsubscribe(void) { prv_missing("compass_service_unsubscribe"); return 0; }
__attribute__((weak)) intptr_t content_indicator_create(void) { prv_missing("content_indicator_create"); return 0; }
__attribute__((weak)) intptr_t content_indicator_destroy(void) { prv_missing("content_indicator_destroy"); return 0; }
__attribute__((weak)) intptr_t content_indicator_get_content_available(void) { prv_missing("content_indicator_get_content_available"); return 0; }
__attribute__((weak)) intptr_t data_logging_create(void) { prv_missing("data_logging_create"); return 0; }
__attribute__((weak)) intptr_t data_logging_finish(void) { prv_missing("data_logging_finish"); return 0; }
__attribute__((weak)) intptr_t data_logging_log(void) { prv_missing("data_logging_log"); return 0; }
__attribute__((weak)) intptr_t dict_calc_buffer_size(void) { prv_missing("dict_calc_buffer_size"); return 0; }
__attribute__((weak)) intptr_t dict_calc_buffer_size_from_tuplets(void) { prv_missing("dict_calc_buffer_size_from_tuplets"); return 0; }
__attribute__((weak)) intptr_t dict_find(void) { prv_missing("dict_find"); return 0; }
__attribute__((weak)) intptr_t dict_merge(void) { prv_missing("dict_merge"); return 0; }
__attribute__((weak)) intptr_t dict_read_begin_from_buffer(void) { prv_missing("dict_read_begin_from_buffer"); return 0; }
__attribute__((weak)) intptr_t dict_read_first(void) { prv_missing("dict_read_first"); return 0; }
__attribute__((weak)) intptr_t dict_read_next(void) { prv_missing("dict_read_next"); return 0; }
__attribute__((weak)) intptr_t dict_serialize_tuplets(void) { prv_missing("dict_serialize_tuplets"); return 0; }
__attribute__((weak)) intptr_t dict_serialize_tuplets_to_buffer(void) { prv_missing("dict_serialize_tuplets_to_buffer"); return 0; }
__attribute__((weak)) intptr_t dict_serialize_tuplets_to_buffer__deprecated(void) { prv_missing("dict_serialize_tuplets_to_buffer__deprecated"); return 0; }
__attribute__((weak)) intptr_t dict_serialize_tuplets_to_buffer_with_iter(void) { prv_missing("dict_serialize_tuplets_to_buffer_with_iter"); return 0; }
__attribute__((weak)) intptr_t dict_size(void) { prv_missing("dict_size"); return 0; }
__attribute__((weak)) intptr_t dict_write_begin(void) { prv_missing("dict_write_begin"); return 0; }
__attribute__((weak)) intptr_t dict_write_cstring(void) { prv_missing("dict_write_cstring"); return 0; }
__attribute__((weak)) intptr_t dict_write_data(void) { prv_missing("dict_write_data"); return 0; }
__attribute__((weak)) intptr_t dict_write_end(void) { prv_missing("dict_write_end"); return 0; }
__attribute__((weak)) intptr_t dict_write_int(void) { prv_missing("dict_write_int"); return 0; }
__attribute__((weak)) intptr_t dict_write_int16(void) { prv_missing("dict_write_int16"); return 0; }
__attribute__((weak)) intptr_t dict_write_int32(void) { prv_missing("dict_write_int32"); return 0; }
__attribute__((weak)) intptr_t dict_write_int8(void) { prv_missing("dict_write_int8"); return 0; }
__attribute__((weak)) intptr_t dict_write_tuplet(void) { prv_missing("dict_write_tuplet"); return 0; }
__attribute__((weak)) intptr_t dict_write_uint16(void) { prv_missing("dict_write_uint16"); return 0; }
__attribute__((weak)) intptr_t dict_write_uint32(void) { prv_missing("dict_write_uint32"); return 0; }
__attribute__((weak)) intptr_t dict_write_uint8(void) { prv_missing("dict_write_uint8"); return 0; }
__attribute__((weak)) intptr_t dictation_session_create(void) { prv_missing("dictation_session_create"); return 0; }
__attribute__((weak)) intptr_t dictation_session_destroy(void) { prv_missing("dictation_session_destroy"); return 0; }
__attribute__((weak)) intptr_t dictation_session_enable_confirmation(void) { prv_missing("dictation_session_enable_confirmation"); return 0; }
__attribute__((weak)) intptr_t dictation_session_enable_error_dialogs(void) { prv_missing("dictation_session_enable_error_dialogs"); return 0; }
__attribute__((weak)) intptr_t dictation_session_start(void) { prv_missing("dictation_session_start"); return 0; }
__attribute__((weak)) intptr_t dictation_session_stop(void) { prv_missing("dictation_session_stop"); return 0; }
__attribute__((weak)) intptr_t health_service_activities_iterate(void) { prv_missing("health_service_activities_iterate"); return 0; }
__attribute__((weak)) intptr_t health_service_aggregate_averaged(void) { prv_missing("health_service_aggregate_averaged"); return 0; }
__attribute__((weak)) intptr_t health_service_any_activity_accessible(void) { prv_missing("health_service_any_activity_accessible"); return 0; }
__attribute__((weak)) intptr_t health_service_cancel_metric_alert(void) { prv_missing("health_service_cancel_metric_alert"); return 0; }
__attribute__((weak)) intptr_t health_service_events_subscribe(void) { prv_missing("health_service_events_subscribe"); return 0; }
__attribute__((weak)) intptr_t health_service_events_unsubscribe(void) { prv_missing("health_service_events_unsubscribe"); return 0; }
__attribute__((weak)) intptr_t health_service_get_heart_rate_sample_period_expiration_sec(void) { prv_missing("health_service_get_heart_rate_sample_period_expiration_sec"); return 0; }
__attribute__((weak)) intptr_t health_service_get_measurement_system_for_display(void) { prv_missing("health_service_get_measurement_system_for_display"); return 0; }
__attribute__((weak)) intptr_t health_service_get_minute_history(void) { prv_missing("health_service_get_minute_history"); return 0; }
__attribute__((weak)) intptr_t health_service_metric_accessible(void) { prv_missing("health_service_metric_accessible"); return 0; }
__attribute__((weak)) intptr_t health_service_metric_aggregate_averaged_accessible(void) { prv_missing("health_service_metric_aggregate_averaged_accessible"); return 0; }
__attribute__((weak)) intptr_t health_service_metric_averaged_accessible(void) { prv_missing("health_service_metric_averaged_accessible"); return 0; }
__attribute__((weak)) intptr_t health_service_peek_current_activities(void) { prv_missing("health_service_peek_current_activities"); return 0; }
__attribute__((weak)) intptr_t health_service_peek_current_value(void) { prv_missing("health_service_peek_current_value"); return 0; }
__attribute__((weak)) intptr_t health_service_peek_hrv_ppi_ms(void) { prv_missing("health_service_peek_hrv_ppi_ms"); return 0; }
__attribute__((weak)) intptr_t health_service_register_metric_alert(void) { prv_missing("health_service_register_metric_alert"); return 0; }
__attribute__((weak)) intptr_t health_service_set_heart_rate_sample_period(void) { prv_missing("health_service_set_heart_rate_sample_period"); return 0; }
__attribute__((weak)) intptr_t health_service_set_hrv_sample_period(void) { prv_missing("health_service_set_hrv_sample_period"); return 0; }
__attribute__((weak)) intptr_t health_service_sum(void) { prv_missing("health_service_sum"); return 0; }
__attribute__((weak)) intptr_t health_service_sum_averaged(void) { prv_missing("health_service_sum_averaged"); return 0; }
__attribute__((weak)) intptr_t health_service_sum_today(void) { prv_missing("health_service_sum_today"); return 0; }
__attribute__((weak)) intptr_t heap_bytes_free(void) { prv_missing("heap_bytes_free"); return 0; }
__attribute__((weak)) intptr_t heap_bytes_used(void) { prv_missing("heap_bytes_used"); return 0; }
__attribute__((weak)) intptr_t memory_cache_flush(void) { prv_missing("memory_cache_flush"); return 0; }
__attribute__((weak)) intptr_t menu_layer_legacy2_create(void) { prv_missing("menu_layer_legacy2_create"); return 0; }
__attribute__((weak)) intptr_t menu_layer_legacy2_set_callbacks(void) { prv_missing("menu_layer_legacy2_set_callbacks"); return 0; }
__attribute__((weak)) intptr_t menu_layer_legacy2_set_callbacks__deprecated(void) { prv_missing("menu_layer_legacy2_set_callbacks__deprecated"); return 0; }
__attribute__((weak)) intptr_t moddable_createMachine(void) { prv_missing("moddable_createMachine"); return 0; }
__attribute__((weak)) intptr_t pan_recognizer_create(void) { prv_missing("pan_recognizer_create"); return 0; }
__attribute__((weak)) intptr_t pan_recognizer_get_delta_since_prev(void) { prv_missing("pan_recognizer_get_delta_since_prev"); return 0; }
__attribute__((weak)) intptr_t pan_recognizer_get_delta_since_start(void) { prv_missing("pan_recognizer_get_delta_since_start"); return 0; }
__attribute__((weak)) intptr_t pan_recognizer_get_total_delta(void) { prv_missing("pan_recognizer_get_total_delta"); return 0; }
__attribute__((weak)) intptr_t pan_recognizer_get_velocity(void) { prv_missing("pan_recognizer_get_velocity"); return 0; }
__attribute__((weak)) intptr_t pbl_localeconv_r(void) { prv_missing("pbl_localeconv_r"); return 0; }
__attribute__((weak)) intptr_t persist_read_data__deprecated(void) { prv_missing("persist_read_data__deprecated"); return 0; }
__attribute__((weak)) intptr_t persist_read_string__deprecated(void) { prv_missing("persist_read_string__deprecated"); return 0; }
__attribute__((weak)) intptr_t persist_write_data__deprecated(void) { prv_missing("persist_write_data__deprecated"); return 0; }
__attribute__((weak)) intptr_t preferred_content_size(void) { prv_missing("preferred_content_size"); return 0; }
__attribute__((weak)) intptr_t preferred_result_display_duration(void) { prv_missing("preferred_result_display_duration"); return 0; }
__attribute__((weak)) intptr_t property_animation_legacy2_destroy(void) { prv_missing("property_animation_legacy2_destroy"); return 0; }
__attribute__((weak)) intptr_t recognizer_set_fail_after(void) { prv_missing("recognizer_set_fail_after"); return 0; }
__attribute__((weak)) intptr_t recognizer_set_simultaneous_with(void) { prv_missing("recognizer_set_simultaneous_with"); return 0; }
__attribute__((weak)) intptr_t rocky_event_loop_with_resource(void) { prv_missing("rocky_event_loop_with_resource"); return 0; }
__attribute__((weak)) intptr_t rot_bitmap_layer_create(void) { prv_missing("rot_bitmap_layer_create"); return 0; }
__attribute__((weak)) intptr_t rot_bitmap_layer_destroy(void) { prv_missing("rot_bitmap_layer_destroy"); return 0; }
__attribute__((weak)) intptr_t rot_bitmap_layer_get_layer(void) { prv_missing("rot_bitmap_layer_get_layer"); return 0; }
__attribute__((weak)) intptr_t rot_bitmap_layer_increment_angle(void) { prv_missing("rot_bitmap_layer_increment_angle"); return 0; }
__attribute__((weak)) intptr_t rot_bitmap_layer_set_angle(void) { prv_missing("rot_bitmap_layer_set_angle"); return 0; }
__attribute__((weak)) intptr_t rot_bitmap_layer_set_corner_clip_color(void) { prv_missing("rot_bitmap_layer_set_corner_clip_color"); return 0; }
__attribute__((weak)) intptr_t rot_bitmap_layer_set_corner_clip_color_2bit(void) { prv_missing("rot_bitmap_layer_set_corner_clip_color_2bit"); return 0; }
__attribute__((weak)) intptr_t rot_bitmap_set_compositing_mode(void) { prv_missing("rot_bitmap_set_compositing_mode"); return 0; }
__attribute__((weak)) intptr_t rot_bitmap_set_src_ic(void) { prv_missing("rot_bitmap_set_src_ic"); return 0; }
__attribute__((weak)) intptr_t simple_menu_layer_create(void) { prv_missing("simple_menu_layer_create"); return 0; }
__attribute__((weak)) intptr_t simple_menu_layer_destroy(void) { prv_missing("simple_menu_layer_destroy"); return 0; }
__attribute__((weak)) intptr_t simple_menu_layer_get_layer(void) { prv_missing("simple_menu_layer_get_layer"); return 0; }
__attribute__((weak)) intptr_t simple_menu_layer_get_menu_layer(void) { prv_missing("simple_menu_layer_get_menu_layer"); return 0; }
__attribute__((weak)) intptr_t simple_menu_layer_get_selected_index(void) { prv_missing("simple_menu_layer_get_selected_index"); return 0; }
__attribute__((weak)) intptr_t simple_menu_layer_set_selected_index(void) { prv_missing("simple_menu_layer_set_selected_index"); return 0; }
__attribute__((weak)) intptr_t speaker_get_status(void) { prv_missing("speaker_get_status"); return 0; }
__attribute__((weak)) intptr_t speaker_is_muted(void) { prv_missing("speaker_is_muted"); return 0; }
__attribute__((weak)) intptr_t speaker_play_notes(void) { prv_missing("speaker_play_notes"); return 0; }
__attribute__((weak)) intptr_t speaker_play_tone(void) { prv_missing("speaker_play_tone"); return 0; }
__attribute__((weak)) intptr_t speaker_play_tracks(void) { prv_missing("speaker_play_tracks"); return 0; }
__attribute__((weak)) intptr_t speaker_set_finish_callback(void) { prv_missing("speaker_set_finish_callback"); return 0; }
__attribute__((weak)) intptr_t speaker_set_volume(void) { prv_missing("speaker_set_volume"); return 0; }
__attribute__((weak)) intptr_t speaker_stop(void) { prv_missing("speaker_stop"); return 0; }
__attribute__((weak)) intptr_t speaker_stream_close(void) { prv_missing("speaker_stream_close"); return 0; }
__attribute__((weak)) intptr_t speaker_stream_open(void) { prv_missing("speaker_stream_open"); return 0; }
__attribute__((weak)) intptr_t speaker_stream_write(void) { prv_missing("speaker_stream_write"); return 0; }
__attribute__((weak)) intptr_t swipe_recognizer_create(void) { prv_missing("swipe_recognizer_create"); return 0; }
__attribute__((weak)) intptr_t swipe_recognizer_get_direction(void) { prv_missing("swipe_recognizer_get_direction"); return 0; }
__attribute__((weak)) intptr_t swipe_recognizer_get_velocity(void) { prv_missing("swipe_recognizer_get_velocity"); return 0; }
__attribute__((weak)) intptr_t sys_clock_get_timezone(void) { prv_missing("sys_clock_get_timezone"); return 0; }
__attribute__((weak)) intptr_t sys_profiler_init(void) { prv_missing("sys_profiler_init"); return 0; }
__attribute__((weak)) intptr_t sys_profiler_print_stats(void) { prv_missing("sys_profiler_print_stats"); return 0; }
__attribute__((weak)) intptr_t sys_profiler_start(void) { prv_missing("sys_profiler_start"); return 0; }
__attribute__((weak)) intptr_t sys_profiler_stop(void) { prv_missing("sys_profiler_stop"); return 0; }
__attribute__((weak)) intptr_t sys_psleep(void) { prv_missing("sys_psleep"); return 0; }
__attribute__((weak)) intptr_t sys_time_start_of_today(void) { prv_missing("sys_time_start_of_today"); return 0; }
__attribute__((weak)) intptr_t sys_watch_info_get_color(void) { prv_missing("sys_watch_info_get_color"); return 0; }
__attribute__((weak)) intptr_t tap_recognizer_create(void) { prv_missing("tap_recognizer_create"); return 0; }
__attribute__((weak)) intptr_t tap_recognizer_get_tap_point(void) { prv_missing("tap_recognizer_get_tap_point"); return 0; }
__attribute__((weak)) intptr_t task_calloc(void) { prv_missing("task_calloc"); return 0; }
__attribute__((weak)) intptr_t task_realloc(void) { prv_missing("task_realloc"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_create(void) { prv_missing("text_layer_legacy2_create"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_destroy(void) { prv_missing("text_layer_legacy2_destroy"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_get_layer(void) { prv_missing("text_layer_legacy2_get_layer"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_get_text(void) { prv_missing("text_layer_legacy2_get_text"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_set_background_color_2bit(void) { prv_missing("text_layer_legacy2_set_background_color_2bit"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_set_font(void) { prv_missing("text_layer_legacy2_set_font"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_set_overflow_mode(void) { prv_missing("text_layer_legacy2_set_overflow_mode"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_set_size(void) { prv_missing("text_layer_legacy2_set_size"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_set_text(void) { prv_missing("text_layer_legacy2_set_text"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_set_text_alignment(void) { prv_missing("text_layer_legacy2_set_text_alignment"); return 0; }
__attribute__((weak)) intptr_t text_layer_legacy2_set_text_color_2bit(void) { prv_missing("text_layer_legacy2_set_text_color_2bit"); return 0; }
__attribute__((weak)) intptr_t touch_service_is_enabled(void) { prv_missing("touch_service_is_enabled"); return 0; }
__attribute__((weak)) intptr_t touch_service_subscribe(void) { prv_missing("touch_service_subscribe"); return 0; }
__attribute__((weak)) intptr_t touch_service_unsubscribe(void) { prv_missing("touch_service_unsubscribe"); return 0; }
__attribute__((weak)) intptr_t watch_info_get_firmware_version(void) { prv_missing("watch_info_get_firmware_version"); return 0; }
__attribute__((weak)) intptr_t watch_info_get_model(void) { prv_missing("watch_info_get_model"); return 0; }
__attribute__((weak)) intptr_t window_attach_recognizer(void) { prv_missing("window_attach_recognizer"); return 0; }
__attribute__((weak)) intptr_t window_detach_recognizer(void) { prv_missing("window_detach_recognizer"); return 0; }
__attribute__((weak)) intptr_t window_get_click_config_context(void) { prv_missing("window_get_click_config_context"); return 0; }
__attribute__((weak)) intptr_t window_get_fullscreen(void) { prv_missing("window_get_fullscreen"); return 0; }
__attribute__((weak)) intptr_t window_set_background_color_2bit(void) { prv_missing("window_set_background_color_2bit"); return 0; }
__attribute__((weak)) intptr_t window_set_touch_bridge_disabled(void) { prv_missing("window_set_touch_bridge_disabled"); return 0; }
__attribute__((weak)) intptr_t worker_event_loop(void) { prv_missing("worker_event_loop"); return 0; }
__attribute__((weak)) intptr_t worker_launch_app(void) { prv_missing("worker_launch_app"); return 0; }
__attribute__((weak)) intptr_t animation_legacy2_get_custom_curve(void) { prv_missing("animation_legacy2_get_custom_curve"); return 0; }

// libc entries the minimal libc does not provide (weak: a real libc wins).
#include <stddef.h>
#include <string.h>
__attribute__((weak)) long atol(const char *s) {
  while (*s == ' ' || *s == '\t') { ++s; }
  int neg = 0;
  if (*s == '-' || *s == '+') { neg = (*s == '-'); ++s; }
  long v = 0;
  while (*s >= '0' && *s <= '9') { v = v * 10 + (*s++ - '0'); }
  return neg ? -v : v;
}
__attribute__((weak)) int atoi(const char *s) { return (int)atol(s); }
__attribute__((weak)) char *strncat(char *dst, const char *src, size_t n) {
  char *d = dst + strlen(dst);
  while (n-- && *src) { *d++ = *src++; }
  *d = '\0';
  return dst;
}
