#!/usr/bin/env python3
"""Emit weak stubs for exported-symbol-table entries the Zephyr port does not
link yet, so the generated pebble.auto.c jump table links and an app calling a
missing entry logs APPLIB_MISSING instead of jumping into the void.

usage: gen_pbl_table_stubs.py <pebble.auto.c> <zephyr.elf>... > pbl_table_stubs.c
"""
import re, subprocess, sys
NM = "/opt/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-nm"
table = sys.argv[1]
provided = None  # symbols defined in EVERY given elf (a board-only provider still gets a weak stub)
for elf in sys.argv[2:]:
    here = set()
    for line in subprocess.run([NM, elf], capture_output=True, text=True).stdout.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[1] in "TtDdBbRr":  # weak = our own stubs, not providers
            here.add(parts[2])
    provided = here if provided is None else provided & here
names = sorted(set(re.findall(r"^extern void ([A-Za-z_0-9]+)\(", open(table).read(), re.M)))
EXTRA = ["animation_legacy2_get_custom_curve"]  # reached via kept sections, not table entries
missing = [n for n in names if n not in provided] + [n for n in EXTRA if n not in provided]
out = ["/* SPDX-License-Identifier: Apache-2.0 */",
       "// Generated by zephyr-port-notes/tools/gen_pbl_table_stubs.py: weak stubs for",
       "// exported-symbol-table entries the port does not link yet. A real",
       "// definition anywhere in the build overrides the stub.",
       "#include <stdint.h>", "#include <zephyr/sys/printk.h>", "",
       "static void prv_missing(const char *name) { printk(\"APPLIB_MISSING %s\\n\", name); }", ""]
for n in missing:
    out.append("__attribute__((weak)) intptr_t %s(void) { prv_missing(\"%s\"); return 0; }" % (n, n))
out += ["", "// libc entries the minimal libc does not provide (weak: a real libc wins).",
        "#include <stddef.h>", "#include <string.h>",
        "__attribute__((weak)) long atol(const char *s) {",
        "  while (*s == ' ' || *s == '\\t') { ++s; }",
        "  int neg = 0;",
        "  if (*s == '-' || *s == '+') { neg = (*s == '-'); ++s; }",
        "  long v = 0;",
        "  while (*s >= '0' && *s <= '9') { v = v * 10 + (*s++ - '0'); }",
        "  return neg ? -v : v;",
        "}",
        "__attribute__((weak)) int atoi(const char *s) { return (int)atol(s); }",
        "__attribute__((weak)) char *strncat(char *dst, const char *src, size_t n) {",
        "  char *d = dst + strlen(dst);",
        "  while (n-- && *src) { *d++ = *src++; }",
        "  *d = '\\0';",
        "  return dst;",
        "}"]
print("\n".join(out))
print("// %d stubs" % len(missing), file=sys.stderr)
